[appdynamics]
[appdynamics]
198.18.134.23 ansible_user=cisco ansible_ssh_password=C1sco12345 ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_become=true ansible_become_password=C1sco12345 ansible_hostname=hostname ansible_python_interpreter=/usr/bin/python3
