apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:POD_IP}:4317
          http:
            endpoint: ${env:POD_IP}:4318
            cors:
              allowed_origins:
                - http://*
                - https://*
    processors:
      resource:
        attributes:
        - key: appdynamics.controller.account
          action: upsert
          value: "fso-tme"
        - key: appdynamics.controller.host
          action: upsert
          value: "fso-tme.saas.appdynamics.com"
        - key: appdynamics.controller.port
          action: upsert
          value: 443
        - key: service.name
          value: notification-service
          action: insert
        - key: service.namespace
          value: Petclinic-X
          action: upsert
      batch:
        timeout: 30s
        send_batch_size: 90
      transform:
        trace_statements:
          - context: span
            conditions:
              - kind == SPAN_KIND_CLIENT
            statements:
              - set(attributes["net.peer.name"], "customers-service") where name == "http:customers-service_8081"
    exporters:
      debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      debug/full:
        verbosity: detailed
      otlp:
        endpoint: "my-splunk-otel-collector-agent.splunk.svc.cluster.local:4317"        
        tls:
          insecure: true  # Set to true if the endpoint doesn't use TLS; otherwise, configure TLS settings appropriately
      otlphttp:
        endpoint: "https://pdx-sls-agent-api.saas.appdynamics.com"
        headers: {"x-api-key": "10bab0c1395eecbb7bbaafbcfb9c54920fc7379fdc9a0ac76339534add0d6133"} #gitleaks:allow this is part of .gitignore
    extensions:
      zpages:
        endpoint: ${env:POD_IP}:56888
    service:
      extensions: [zpages]
      pipelines:
        traces/fso:
          receivers: [otlp]
          processors: [transform, resource, batch]
          exporters: [otlphttp, debug]      
        logs:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [otlp]