[monitor:///home/cisco/spring-petclinic-microservices/deployments/hybrid/java/app.log]
#  Sets the source type.  This is crucial for Splunk to understand
#  the format of your data.  If Splunk doesn't have a pre-defined
#  sourcetype, you can create your own in props.conf.
sourcetype = _raw

#  Sets the index to store the data.  "main" is the default.
#  Change this if you want to store the data in a different index.
index = clus_logs

#  (Optional) Sets the host.  If not set, Splunk will use the hostname
#  of the machine where the data is coming from.
host = visits-service-x
