apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-cm
data:
  agent.js: |
    console.log("agent.js loaded");

    window["adrum-start-time"] = new Date().getTime();
    (function(config){
        config.appKey = "AD-AAB-ADY-VGC";
        config.adrumExtUrlHttp = "http://cdn.appdynamics.com";
        config.adrumExtUrlHttps = "https://cdn.appdynamics.com";
        config.beaconUrlHttp = "http://pdx-col.eum-appdynamics.com";
        config.beaconUrlHttps = "https://pdx-col.eum-appdynamics.com";
        config.useHTTPSAlways = true;
        config.xd = {"enable":true};
        config.resTiming = {"sampler":"RelevantN","maxNum":20,"bufSize":200,"clearResTimingOnBeaconSend":true};
        config.maxUrlLength = 512;
        config.spa = {"spa2":true};
        config.releaseId = "clus";
        config.enableCoreWebVitals = true;
        config.enableSpeedIndex = true;
    })(window["adrum-config"] || (window["adrum-config"] = {}));
