apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  annotations:
    metallb.universe.tf/address-pool: default-addresspool
    metallb.universe.tf/allow-shared-ip: cl25us
spec:
  type: LoadBalancer  # Use ClusterIP for internal access; change to NodePort or LoadBalancer if external access is needed
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318